'''
Keeper of Constant variables
'''


#STEREO CAMERA
STEREOCAM_GND_HEIGHT = 0 #NOTE: NEEDS ACTUALLY SET
STEREOCAM_HORZ_DEG_VIEW = 45 #NOTE: NEEDS ACTUALLY SET
STEREOCAM_VERT_DEG_VIEW = 45 #NOTE: NEEDS ACTUALLY SET #Not sure if we'll use

#TELESCOPIC CAMERA
TELECAM_PORT=0 #NOTE: NEEDS ACTUALLY SET
TELECAM_GND_HEIGHT = 0 #NOTE: NEEDS ACTUALLY SET #Not sure if we'll use
TELECAM_HORZ_DEG_VIEW = 45 #NOTE: NEEDS ACTUALLY SET
TELECAM_VERT_DEG_VIEW = 45 #NOTE: NEEDS ACTUALLY SET #Not sure if we'll use

#SERIAL COMMUNICATIONS
ESP32_PORT=0 #NOTE: NEEDS ACTUALLY SET

#MAIN
STEREOCAM_MODELPATH = "" #NOTE: NEEDS ACTUALLY SET
TELECAM_MODELPATH = "" #NOTE: NEEDS ACTUALLY SET
CROPCOMPR_FILEPATH = "" #NOTE: NEEDS ACTUALLY SET #end with '/'