'''
Keeper of Constant variables
'''


#STEREO CAMERA
STEREOCAM_GND_HEIGHT = 0
STEREOCAM_HORZ_DEG_VIEW = 45
STEREOCAM_VERT_DEG_VIEW = 45 #Not sure if we'll use

#TELESCOPIC CAMERA
TELECAM_PORT=0
TELECAM_GND_HEIGHT = 0 #Not sure if we'll use
TELECAM_HORZ_DEG_VIEW = 45
TELECAM_VERT_DEG_VIEW = 45 #Not sure if we'll use

#SERIAL COMMUNICATIONS
ESP32_PORT=0

#MAIN
STEREOCAM_MODELPATH = ""
TELECAM_MODELPATH = ""
CROPCOMPR_FILEPATH = "" #end with '/'