'''
Keeper of Constant variables
'''


#STEREO CAMERA
STEREOCAM_GND_HEIGHT = 0 #NOTE: NEEDS ACTUALLY SET
STEREOCAM_HORZ_DEG_VIEW = 135 #https://www.carnegierobotics.com/AutonomousVehicles/CameraManufacturing/StereoCameraManufacturing/KS21i/Files/KS21i_Data_Sheet_CRL.pdf
STEREOCAM_VERT_DEG_VIEW = 84

#TELESCOPIC CAMERA
TELECAM_PORT=0 #NOTE: NEEDS ACTUALLY SET
TELECAM_GND_HEIGHT = 0 #NOTE: NEEDS ACTUALLY SET #Not sure if we'll use
TELECAM_FOCAL_LENGTH =  135# 18mm shortest, 135 highest zoom

#SERIAL COMMUNICATIONS
ESP32_PORT=0 #NOTE: NEEDS ACTUALLY SET

#MAIN
STEREOCAM_MODELPATH = "" #NOTE: NEEDS ACTUALLY SET
TELECAM_MODELPATH = "" #NOTE: NEEDS ACTUALLY SET
CROPCOMPR_FILEPATH = "" #NOTE: NEEDS ACTUALLY SET #end with '/'